name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./client
      
    - name: Build
      run: npm run build
      working-directory: ./client
      env:
        VITE__API_KEY: ${{ secrets.VITE__API_KEY }}
        VITE__AUTH_DOMAIN: ${{ secrets.VITE__AUTH_DOMAIN }}
        VITE__PROJECT_ID: ${{ secrets.VITE__PROJECT_ID }}
        VITE__STORAGE_BUCKET: ${{ secrets.VITE__STORAGE_BUCKET }}
        VITE__MESSAGING_SENDER_ID: ${{ secrets.VITE__MESSAGING_SENDER_ID }}
        VITE__APP_ID: ${{ secrets.VITE__APP_ID }}
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/dist
        cname: # カスタムドメインがある場合はここに設定
